### ISSUE TITLE
[Compatibility] Hexerei

### ISSUE THREAD

**Issue by Rhyssia** [EwyBoy/SeedDrop#12]
**Name of mod you want compatibility with?**
Hexerei

**Is your compatibility request related to a problem?**
When overriding what seeds drop when grass breaks, it prevents some mods (Hexerei in this example) from modifying grass break drops the way the mod author designed.

**Describe the solution you'd like**
Config Option to integrate/override other mods modifying grass drops

**Additional context**
Not Applicable.

**Comment by EwyBoy** [comment]
The easiest way to solve this when both mods are installed is to simple add the seeds you want to drop to the drop list of seed drop. This can easily be done in-game using commands or in the config file. There is no need for a custom integration for this.

**Comment by Rhyssia** [comment]
Ahem, thank you for evaluating this issue.
