### ISSUE TITLE
Config having empty lines crashes on startup

### ISSUE THREAD

**Issue by MuuKnew** [EwyBoy/SeedDrop#2]
[crash-2019-01-03_03.15.54-client.txt](https://github.com/EwyBoy/SeedDrop/files/2723028/crash-2019-01-03_03.15.54-client.txt)

Crash detailed above in log file, this was the only mod in the pack

Config which crashed (minus extraneous bits):

general {
    S:"SeedDrop Drop List" <
        minecraft:beetroot_seeds
        10

     >
}

Removing the empty line after 10 allowed the crash to not happen.

If it can't be fixed for whatever reason, a comment detailing this in the config would be cool.

Thanks for the great mod.

**Comment by EwyBoy** [comment]
I think forge changed how config files are formatted and this is now causing a crash since the mod is built to run on a very old version of forge. I will update the mod to support the latest forge version ASAP.
Thanks for your crash report.

**Comment by EwyBoy** [comment]
I fixed the issue for all versions of the mod, from 1.8 to 1.12.
https://minecraft.curseforge.com/projects/seed-drop/files
