### ISSUE TITLE
feature request: ability to stop wheat seed drops

### ISSUE THREAD

**Issue by Mumberthrax** [EwyBoy/SeedDrop#3]
Even when adding other drops, wheat seeds still drop from breaking grass. It would be nice if there was a means to disable this.

Alternatively, if it is only possible to _add_ items to the list of possible drops, it would be nice to be able to add in some sort of empty stack with such a high chance that it is basically impossible for wheat seeds to be selected. Supposedly the hunger overhaul mod can disable seeds dropping from breaking tall grass but it does not seem to work.

**Comment by EwyBoy** [comment]
Sadly this is not possible. I have not found a way to directly edit the grass drop table. Just add entires to it. I can't also just give a thing a super hight chance of dropping they way you descripe because that is not the way forge made their system.

**Comment by Mumberthrax** [comment]
I understand. Is there a way to add an empty itemstack instead of specifying a particular item? After i made this github issue i went and was able to use kubejs to do this, but I don't know if there is a way to just pop it into the config file for SeedDrop, or if it would need a special case for a variable name or something:

```
events.listen("postinit", function (event) {
  MinecraftForge = Java.type("net.minecraftforge.common.MinecraftForge");
  var seed = item.empty.itemStack;
  MinecraftForge.addGrassSeed(seed, 100000000);
});
```

unfortunately it doesn't seem to affect double-tall grass but it's something i guess.

**Comment by EwyBoy** [comment]
I can look into this when I find the time. Could be possible.

**Comment by EwyBoy** [comment]
This can be done in Seed Drop 2 by removing all entries in the new config.
https://www.curseforge.com/minecraft/mc-mods/seed-drop
