### ISSUE TITLE
[Bug] Classloading crash

### ISSUE THREAD

**Issue by COLDW0LF** [EwyBoy/SeedDrop#6]
###### **Minecraft Version**
> 1.16.5

###### **Forge Version**
> 36.1.24

###### **Mod Version**
> 2.0.2

###### **Describe the bug**
> Crashing on world load when installed with Mekanism. If either mod is used separately, the game loads.

###### **How to reproduce**
Install with Mekanism. Game fails to load when loading loot drops.

###### **Link to [crashlog](https://gist.github.com/)** *[If Applicable]*
https://gist.github.com/COLDW0LF/c45080432a172faad5a9219c370504a5

**Comment by EwyBoy** [comment]
Gonna look into this and try to resolve the issue on my side.
Thanks for bringing this to my attention.

**Comment by COLDW0LF** [comment]
No worries! If you need me to test anything other variables for you, feel free to let me know.
