### ISSUE TITLE
[Bug] Modded Shears Don't Work Properly

### ISSUE THREAD

**Issue by Darkehart** [EwyBoy/SeedDrop#8]
###### **Minecraft Version**
> 1.16.5

###### **Forge Version**
> 36.2.8

###### **Mod Version**
> 2.1.1

###### **Describe the bug**
> When using any shear other than the vanilla one, the tall grass breaks and gives seed drops instead of dropping itself.

###### **How to reproduce**
> Left-click a tall grass while holding any modded shear, including the Tinker's Construct kama.

###### **Link to [crashlog](https://gist.github.com/)** *[If Applicable]*
> N/A

###### **Screenshots / Images**
> N/A

**Comment by EwyBoy** [comment]
Ahh a little oversight there!
Thank you! I will scramble together a solution for this issue as fast as possible.

-Ewy

**Comment by Darkehart** [comment]
No worries. It's the kind of small thing that I only noticed 'cause I was making a whole bunch of redstone roots all at once in Oceanblock, so I decided I would just make one pair of manasteel shears instead of potentially needing another iron shears later on. ^.^

**Comment by EwyBoy** [comment]
Fixed: https://www.curseforge.com/minecraft/mc-mods/seed-drop/files/3521388
