### ISSUE TITLE
[Bug] Seed Drop isn't Tagged for 1.18.1 on CurseForge

### ISSUE THREAD

**Issue by coldReactive** [EwyBoy/SeedDrop#9]
###### **Minecraft Version**
> 1.18.1

###### **Forge Version**
> 39.0.10

###### **Mod Version**
> 2.1.3

###### **Describe the bug**
> CurseForge doesn't show this in Add More Content for 1.18.1 Packs

###### **How to reproduce**
> Search for the mod in CurseForge on a 1.18.1 Modpack

###### **Screenshots / Images**
![image](https://user-images.githubusercontent.com/1313673/148059439-0639f348-167a-4143-9443-0c9eed42c228.png)

**Comment by EwyBoy** [comment]
Ohhh, I thought it was.
Thanks for the report. Its fixed now. Might take some time for CF App to update.
